"Filed out from Dolphin Smalltalk 7"!

PackageManifest subclass: #ManifestBootstrapExamples
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ManifestBootstrapExamples guid: (GUID fromString: '{9a326483-2c1f-4919-b703-3deec9a8cdad}')!
ManifestBootstrapExamples comment: 'ManifestBootstrapExamples class	instanceVariableNames: '''''!
!ManifestBootstrapExamples categoriesForClass!Bootstrap4-Examples-Manifest! !
!ManifestBootstrapExamples class methodsFor!

ruleRBStringConcatenationRuleV1FalsePositive	^ #(#(#(#RGMethodDefinition #(#SBSTypographieExample #renderExampleOn: #false)) #'2019-04-30T20:55:07.149209+02:00') )! !
!ManifestBootstrapExamples class categoriesFor: #ruleRBStringConcatenationRuleV1FalsePositive!code/critics!public! !

