"Filed out from Dolphin Smalltalk 7"!

SBSHeadingTag subclass: #SBSAlertHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSAlertHeadingTag guid: (GUID fromString: '{22f0a2fb-c923-431f-a0d4-a1797c8cfaa9}')!
SBSAlertHeadingTag comment: 'Bootstrap alert heading'!
!SBSAlertHeadingTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSAlertHeadingTag methodsFor!

defaultStyleClass	^'alert-heading'! !
!SBSAlertHeadingTag categoriesFor: #defaultStyleClass!defaults!public! !

