"Filed out from Dolphin Smalltalk 7"!

SBSAnchorTag subclass: #SBSAlertLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSAlertLinkTag guid: (GUID fromString: '{31c1c99f-cfe8-47c2-843e-984d7105921c}')!
SBSAlertLinkTag comment: 'A boostrap alert link'!
!SBSAlertLinkTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSAlertLinkTag methodsFor!

defaultStyleClass	^'alert-link'! !
!SBSAlertLinkTag categoriesFor: #defaultStyleClass!defaults!public! !

