"Filed out from Dolphin Smalltalk 7"!

SBSListItemTag subclass: #SBSBreadcrumbSectionTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSBreadcrumbSectionTag guid: (GUID fromString: '{8aa7154e-16ae-4a51-bdf7-5a6ec3aca0d2}')!
SBSBreadcrumbSectionTag comment: 'A Bootstrap breadcrumb section'!
!SBSBreadcrumbSectionTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSBreadcrumbSectionTag methodsFor!

defaultStyleClass	^'breadcrumb-item'! !
!SBSBreadcrumbSectionTag categoriesFor: #defaultStyleClass!defaults!public! !

