"Filed out from Dolphin Smalltalk 7"!

SBSButtonGroupTag subclass: #SBSButtonToolbarTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSButtonToolbarTag guid: (GUID fromString: '{e451c6f3-6787-4676-a34f-39ed89209fb8}')!
SBSButtonToolbarTag comment: 'A button toolbar'!
!SBSButtonToolbarTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSButtonToolbarTag methodsFor!

defaultStyleClass	^'btn-toolbar'! !
!SBSButtonToolbarTag categoriesFor: #defaultStyleClass!defaults!public! !

