"Filed out from Dolphin Smalltalk 7"!

SBSButtonGroupTag subclass: #SBSButtonGroupVerticalTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSButtonGroupVerticalTag guid: (GUID fromString: '{3a6b6e0f-7f8d-4aad-9581-484b864d700d}')!
SBSButtonGroupVerticalTag comment: 'Vertical button group for Bootstrap'!
!SBSButtonGroupVerticalTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSButtonGroupVerticalTag methodsFor!

defaultStyleClass	^'btn-group-vertical'! !
!SBSButtonGroupVerticalTag categoriesFor: #defaultStyleClass!defaults!public! !

