"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardGroupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardGroupTag guid: (GUID fromString: '{6ccadefd-256b-45b3-9b61-23043269e69f}')!
SBSCardGroupTag comment: 'Similar to a card deck. The only difference is that the card group removes left and right margins between each card.'!
!SBSCardGroupTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardGroupTag methodsFor!

defaultStyleClass	^'card-group'! !
!SBSCardGroupTag categoriesFor: #defaultStyleClass!defaults!public! !

