"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardImageOverlayTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardImageOverlayTag guid: (GUID fromString: '{fc9593bb-9595-4271-87c0-ae6a5b68d1bc}')!
SBSCardImageOverlayTag comment: 'An image overlay for a Bootstrap card'!
!SBSCardImageOverlayTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardImageOverlayTag methodsFor!

defaultStyleClass	^'card-img-overlay'! !
!SBSCardImageOverlayTag categoriesFor: #defaultStyleClass!defaults!public! !

