"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardBodyTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardBodyTag guid: (GUID fromString: '{53b5b862-6e26-41f2-8cc8-07ae37590fcf}')!
SBSCardBodyTag comment: 'Body of a bootstrap card.'!
!SBSCardBodyTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardBodyTag methodsFor!

defaultStyleClass	^'card-body'! !
!SBSCardBodyTag categoriesFor: #defaultStyleClass!defaults!public! !

