"Filed out from Dolphin Smalltalk 7"!

SBSCardTitleTag subclass: #SBSCardSubtitleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardSubtitleTag guid: (GUID fromString: '{dc029a0d-9e29-43f0-b3fe-338dfb2e7c0c}')!
SBSCardSubtitleTag comment: 'Subtitle for a Bootstrap card'!
!SBSCardSubtitleTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardSubtitleTag methodsFor!

defaultStyleClass	^'card-subtitle'! !
!SBSCardSubtitleTag categoriesFor: #defaultStyleClass!defaults!public! !

