"Filed out from Dolphin Smalltalk 7"!

SBSAnchorTag subclass: #SBSCardLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardLinkTag guid: (GUID fromString: '{1cf8f718-9af1-453b-9c86-ed682a93e947}')!
SBSCardLinkTag comment: 'Links on Bootstrap cards'!
!SBSCardLinkTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardLinkTag methodsFor!

defaultStyleClass	^'card-link'! !
!SBSCardLinkTag categoriesFor: #defaultStyleClass!defaults!public! !

