"Filed out from Dolphin Smalltalk 7"!

SBSImageTag subclass: #SBSCardImageBottomTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardImageBottomTag guid: (GUID fromString: '{1a43e6f0-aeb4-4188-a5c9-ace28077b05d}')!
SBSCardImageBottomTag comment: 'An image at the bottom of a Boostrap card'!
!SBSCardImageBottomTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardImageBottomTag methodsFor!

defaultStyleClass	^'card-img-bottom'! !
!SBSCardImageBottomTag categoriesFor: #defaultStyleClass!defaults!public! !

