"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCarouselItemTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCarouselItemTag guid: (GUID fromString: '{d2b33f98-111e-4904-ac78-af9fe60548d9}')!
SBSCarouselItemTag comment: 'A carousel item'!
!SBSCarouselItemTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCarouselItemTag methodsFor!

active	self class: 'active'!

defaultStyleClass	^'carousel-item'! !
!SBSCarouselItemTag categoriesFor: #active!options!public! !
!SBSCarouselItemTag categoriesFor: #defaultStyleClass!defaults!public! !

