"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCollapseTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCollapseTag guid: (GUID fromString: '{5ab47486-d8c5-424c-9156-0b10aa87cbd0}')!
SBSCollapseTag comment: 'Collapsible section'!
!SBSCollapseTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCollapseTag methodsFor!

defaultStyleClass	^'collapse'!

show	self class: 'show'! !
!SBSCollapseTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSCollapseTag categoriesFor: #show!options!public! !

