"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardColumnsTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardColumnsTag guid: (GUID fromString: '{67b0fa99-2e14-4bb5-9282-2130af8c83db}')!
SBSCardColumnsTag comment: 'Creates a masonry-like grid of cards (like pinterest). The layout will automatically adjust as you insert more cards.'!
!SBSCardColumnsTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardColumnsTag methodsFor!

defaultStyleClass	^'card-columns' ! !
!SBSCardColumnsTag categoriesFor: #defaultStyleClass!defaults!public! !

