"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardDeckTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardDeckTag guid: (GUID fromString: '{d2ade84d-1ea6-4eaf-8e60-ed2ec0f7aa91}')!
SBSCardDeckTag comment: 'Provides a grid of cards that are of equal height and width. The layout will automatically adjust as you insert more cards.'!
!SBSCardDeckTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardDeckTag methodsFor!

defaultStyleClass	^'card-deck'! !
!SBSCardDeckTag categoriesFor: #defaultStyleClass!defaults!public! !

