"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCarouselTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCarouselTag guid: (GUID fromString: '{1038fbc5-3f67-48f4-a707-d7cd6434acc4}')!
SBSCarouselTag comment: 'Bootstrap carousel'!
!SBSCarouselTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCarouselTag methodsFor!

defaultStyleClass	^'carousel'!

slide	self class: 'slide'! !
!SBSCarouselTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSCarouselTag categoriesFor: #slide!options!public! !

