"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardHeaderTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardHeaderTag guid: (GUID fromString: '{c7202f01-0832-4f0a-af56-82aecff80ee6}')!
SBSCardHeaderTag comment: 'Header for Bootstrap card'!
!SBSCardHeaderTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardHeaderTag methodsFor!

defaultStyleClass	^'card-header'! !
!SBSCardHeaderTag categoriesFor: #defaultStyleClass!defaults!public! !

