"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSCardFooterTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardFooterTag guid: (GUID fromString: '{55eefe38-77e6-4151-8f11-4b70faa0460d}')!
SBSCardFooterTag comment: 'Footer for Bootstrap card'!
!SBSCardFooterTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardFooterTag methodsFor!

defaultStyleClass	^'card-footer'! !
!SBSCardFooterTag categoriesFor: #defaultStyleClass!defaults!public! !

