"Filed out from Dolphin Smalltalk 7"!

SBSHeadingTag subclass: #SBSCardTitleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardTitleTag guid: (GUID fromString: '{9f3a4946-2ded-449e-8663-59a99272becc}')!
SBSCardTitleTag comment: 'A card title'!
!SBSCardTitleTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardTitleTag methodsFor!

defaultStyleClass	^'card-title'! !
!SBSCardTitleTag categoriesFor: #defaultStyleClass!defaults!public! !

