"Filed out from Dolphin Smalltalk 7"!

SBSImageTag subclass: #SBSCardImageTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSCardImageTag guid: (GUID fromString: '{8b4d46ab-7ae9-49cc-9047-5e7ed6412818}')!
SBSCardImageTag comment: 'An image on top of a Boostrap card'!
!SBSCardImageTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSCardImageTag methodsFor!

defaultStyleClass	^'card-img-top'! !
!SBSCardImageTag categoriesFor: #defaultStyleClass!defaults!public! !

