"Filed out from Dolphin Smalltalk 7"!

SBSHeadingTag subclass: #SBSDropdownHeaderTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSDropdownHeaderTag guid: (GUID fromString: '{7d0a3b33-7762-408b-8478-506e746db000}')!
SBSDropdownHeaderTag comment: 'A drop down header'!
!SBSDropdownHeaderTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSDropdownHeaderTag methodsFor!

defaultStyleClass	^'dropdown-header'! !
!SBSDropdownHeaderTag categoriesFor: #defaultStyleClass!defaults!public! !

