"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSDropdownMenuTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSDropdownMenuTag guid: (GUID fromString: '{1a5d8afb-0cde-477f-96d4-f197d9c42d95}')!
SBSDropdownMenuTag comment: 'Dropdown menu for Bootstrap'!
!SBSDropdownMenuTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSDropdownMenuTag methodsFor!

defaultStyleClass	^'dropdown-menu'!

dropRight	self class: 'dropdown-menu-right'! !
!SBSDropdownMenuTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSDropdownMenuTag categoriesFor: #dropRight!options!public! !

