"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSDropdownTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSDropdownTag guid: (GUID fromString: '{be7daefd-6d62-4a5f-ac76-e8f24b9676b3}')!
SBSDropdownTag comment: 'A bootstrap dropdown'!
!SBSDropdownTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSDropdownTag methodsFor!

defaultStyleClass	^'dropdown'!

dropLeft	self class: 'dropleft'!

dropRight	self class: 'dropright'!

show	self class: 'show'! !
!SBSDropdownTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSDropdownTag categoriesFor: #dropLeft!operations!public! !
!SBSDropdownTag categoriesFor: #dropRight!operations!public! !
!SBSDropdownTag categoriesFor: #show!operations!public! !

