"Filed out from Dolphin Smalltalk 7"!

WAHeadingTag subclass: #SBSDisplayHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSDisplayHeadingTag guid: (GUID fromString: '{2e51dd2f-bbf0-4ea3-ab16-e07567d2f9a4}')!
SBSDisplayHeadingTag comment: 'A Bootstrap display heading'!
!SBSDisplayHeadingTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSDisplayHeadingTag methodsFor!

level: aLevel	super level: aLevel.	self class: 'display-', self level greaseString! !
!SBSDisplayHeadingTag categoriesFor: #level:!accessing!public! !

