"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSDropupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSDropupTag guid: (GUID fromString: '{2e704f24-32e4-4277-ad1d-4044a1d34a91}')!
SBSDropupTag comment: 'A bootstrap dropup'!
!SBSDropupTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSDropupTag methodsFor!

defaultStyleClass	^'dropup'! !
!SBSDropupTag categoriesFor: #defaultStyleClass!defaults!public! !

