"Filed out from Dolphin Smalltalk 7"!

SBSLayoutTag subclass: #SBSEqualWidthColumnsOnMultipleRowsTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSEqualWidthColumnsOnMultipleRowsTag guid: (GUID fromString: '{55782c54-9cfc-4b9a-adc2-7c05476bd0d8}')!
SBSEqualWidthColumnsOnMultipleRowsTag comment: ''!
!SBSEqualWidthColumnsOnMultipleRowsTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSEqualWidthColumnsOnMultipleRowsTag methodsFor!

defaultStyleClass	^'w-100'! !
!SBSEqualWidthColumnsOnMultipleRowsTag categoriesFor: #defaultStyleClass!defaults!public! !

