"Filed out from Dolphin Smalltalk 7"!

WAFileMetadataLibrary subclass: #SBSFileLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSFileLibrary guid: (GUID fromString: '{54ce0b8d-9ed3-4b8f-b7e7-826d23ac8391}')!
SBSFileLibrary comment: 'SBSFileLibrary subclass: #SBSDeploymentLibrary	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Bootstrap4-Core-Libraries'''!
!SBSFileLibrary categoriesForClass!Bootstrap4-Core-Libraries! !
