"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSFormGroupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSFormGroupTag guid: (GUID fromString: '{926d1a8d-dbfe-44d5-a2cd-8f2597e9ae3c}')!
SBSFormGroupTag comment: 'A boostrap form group'!
!SBSFormGroupTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSFormGroupTag methodsFor!

defaultStyleClass	^'form-group'!

formCheck	self class: 'form-check'! !
!SBSFormGroupTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSFormGroupTag categoriesFor: #formCheck!options!public! !

