"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSJumbotronTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSJumbotronTag guid: (GUID fromString: '{90ef705c-2ecc-49c1-816b-4a85c8d7f651}')!
SBSJumbotronTag comment: 'Bootstrap jumbotron'!
!SBSJumbotronTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSJumbotronTag methodsFor!

beFluid	self class: 'jumbotron-fluid'!

defaultStyleClass	^'jumbotron'! !
!SBSJumbotronTag categoriesFor: #beFluid!options!public! !
!SBSJumbotronTag categoriesFor: #defaultStyleClass!defaults!public! !

