"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSLayoutTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSLayoutTag guid: (GUID fromString: '{bcfaf140-cbff-4b15-b656-375d41ff707a}')!
SBSLayoutTag comment: 'SBSLayoutTag class	instanceVariableNames: '''''!
!SBSLayoutTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSLayoutTag class methodsFor!

isAbstract	^self name = #SBSLayoutTag! !
!SBSLayoutTag class categoriesFor: #isAbstract!public!testing! !

