"Filed out from Dolphin Smalltalk 7"!

SBSLayoutTag subclass: #SBSLayoutRowTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSLayoutRowTag guid: (GUID fromString: '{83ef9fc2-b8d0-41b9-be29-738ad393008d}')!
SBSLayoutRowTag comment: 'A boostrap layout row'!
!SBSLayoutRowTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSLayoutRowTag methodsFor!

alignItemsBaseline	self class: 'align-items-baseline'!

alignItemsBaselineLarge	self class: 'align-items-lg-baseline'!

alignItemsBaselineMedium	self class: 'align-items-md-baseline'!

alignItemsBaselineSmall	self class: 'align-items-sm-baseline'!

alignItemsBaselineVeryLarge	self class: 'align-items-xl-baseline'!

alignItemsCenter	self class: 'align-items-center'!

alignItemsCenterLarge	self class: 'align-items-lg-center'!

alignItemsCenterMedium	self class: 'align-items-md-center'!

alignItemsCenterSmall	self class: 'align-items-sm-center'!

alignItemsCenterVeryLarge	self class: 'align-items-xl-center'!

alignItemsEnd	self class: 'align-items-end'!

alignItemsEndLarge	self class: 'align-items-lg-end'!

alignItemsEndMedium	self class: 'align-items-md-end'!

alignItemsEndSmall	self class: 'align-items-sm-end'!

alignItemsEndVeryLarge	self class: 'align-items-xl-end'!

alignItemsStart	self class: 'align-items-start'!

alignItemsStartLarge	self class: 'align-items-lg-start'!

alignItemsStartMedium	self class: 'align-items-md-start'!

alignItemsStartSmall	self class: 'align-items-sm-start'!

alignItemsStartVeryLarge	self class: 'align-items-xl-start'!

alignItemsStretch	self class: 'align-items-stretch'!

alignItemsStretchLarge	self class: 'align-items-lg-stretch'!

alignItemsStretchMedium	self class: 'align-items-md-stretch'!

alignItemsStretchSmall	self class: 'align-items-sm-stretch'!

alignItemsStretchVeryLarge	self class: 'align-items-xl-stretch'!

defaultStyleClass	^'row'!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'!

noGutters	self class: 'no-gutters'! !
!SBSLayoutRowTag categoriesFor: #alignItemsBaseline!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsBaselineLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsBaselineMedium!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsBaselineSmall!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsBaselineVeryLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsCenter!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsCenterLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsCenterMedium!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsCenterSmall!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsCenterVeryLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsEnd!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsEndLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsEndMedium!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsEndSmall!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsEndVeryLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStart!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStartLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStartMedium!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStartSmall!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStartVeryLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStretch!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStretchLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStretchMedium!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStretchSmall!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #alignItemsStretchVeryLarge!alignment vertical!public! !
!SBSLayoutRowTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentAround!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentAroundLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentAroundMedium!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentAroundSmall!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentAroundVeryLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentBetween!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentBetweenLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentBetweenMedium!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentBetweenSmall!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentBetweenVeryLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentCenter!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentCenterLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentCenterMedium!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentCenterSmall!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentCenterVeryLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentEnd!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentEndLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentEndMedium!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentEndSmall!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentEndVeryLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentStart!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentStartLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentStartMedium!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentStartSmall!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #justifyContentStartVeryLarge!alignment horizontal!public! !
!SBSLayoutRowTag categoriesFor: #noGutters!options!public! !

