"Filed out from Dolphin Smalltalk 7"!

SBSAnchorTag subclass: #SBSNavigationBarBrandTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSNavigationBarBrandTag guid: (GUID fromString: '{a889e3ed-c7f8-469b-93b9-bd463237c3b7}')!
SBSNavigationBarBrandTag comment: 'Clickable navigation bar brand'!
!SBSNavigationBarBrandTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSNavigationBarBrandTag methodsFor!

defaultStyleClass	^'navbar-brand'! !
!SBSNavigationBarBrandTag categoriesFor: #defaultStyleClass!defaults!public! !

