"Filed out from Dolphin Smalltalk 7"!

SBSNavTag subclass: #SBSNavigationTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSNavigationTag guid: (GUID fromString: '{256dd5b3-1f07-4afd-997b-1820a81f8bfa}')!
SBSNavigationTag comment: 'Bootstrap navigation'!
!SBSNavigationTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSNavigationTag methodsFor!

defaultStyleClass	^'nav'!

flex	self class: 'd-flex'!

flexColumn	self class: 'flex-column'!

flexColumnLarge	self class: 'flex-lg-column'!

flexColumnLargeReverse	self class: 'flex-lg-column-reverse'!

flexColumnMedium	self class: 'flex-md-column'!

flexColumnMediumReverse	self class: 'flex-md-column-reverse'!

flexColumnReverse	self class: 'flex-column-reverse'!

flexColumnSmall	self class: 'flex-sm-column'!

flexColumnSmallReverse	self class: 'flex-sm-column-reverse'!

flexColumnVeryLarge	self class: 'flex-xl-column'!

flexColumnVeryLargeReverse	self class: 'flex-xl-column-reverse'!

flexInline	self class: 'd-inline-flex'!

flexLarge	self class: 'd-lg-flex'!

flexLargeInline	self class: 'd-lg-inline-flex'!

flexMedium	self class: 'd-md-flex'!

flexMediumInline	self class: 'd-md-inline-flex'!

flexRow	self class: 'flex-row'!

flexRowLarge	self class: 'flex-lg-row'!

flexRowLargeReverse	self class: 'flex-lg-row-reverse'!

flexRowMedium	self class: 'flex-md-row'!

flexRowMediumReverse	self class: 'flex-md-row-reverse'!

flexRowReverse	self class: 'flex-row-reverse'!

flexRowSmall	self class: 'flex-sm-row'!

flexRowSmallReverse	self class: 'flex-sm-row-reverse'!

flexRowVeryLarge	self class: 'flex-xl-row'!

flexRowVeryLargeReverse	self class: 'flex-xl-row-reverse'!

flexSmall	self class: 'd-sm-flex'!

flexSmallInline	self class: 'd-sm-inline-flex'!

flexVeryLarge	self class: 'd-xl-flex'!

flexVeryLargeInline	self class: 'd-xl-inline-flex'!

initialize	super initialize.	self class: self defaultStyleClass!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !
!SBSNavigationTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSNavigationTag categoriesFor: #flex!container!public! !
!SBSNavigationTag categoriesFor: #flexColumn!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnLarge!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnLargeReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnMedium!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnMediumReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnSmall!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnSmallReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnVeryLarge!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexColumnVeryLargeReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexInline!container!public! !
!SBSNavigationTag categoriesFor: #flexLarge!container!public! !
!SBSNavigationTag categoriesFor: #flexLargeInline!container!public! !
!SBSNavigationTag categoriesFor: #flexMedium!container!public! !
!SBSNavigationTag categoriesFor: #flexMediumInline!container!public! !
!SBSNavigationTag categoriesFor: #flexRow!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowLarge!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowLargeReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowMedium!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowMediumReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowSmall!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowSmallReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowVeryLarge!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexRowVeryLargeReverse!alignment direction!public! !
!SBSNavigationTag categoriesFor: #flexSmall!container!public! !
!SBSNavigationTag categoriesFor: #flexSmallInline!container!public! !
!SBSNavigationTag categoriesFor: #flexVeryLarge!container!public! !
!SBSNavigationTag categoriesFor: #flexVeryLargeInline!container!public! !
!SBSNavigationTag categoriesFor: #initialize!initialization!public! !
!SBSNavigationTag categoriesFor: #justifyContentAround!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentAroundLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentAroundMedium!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentAroundSmall!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentAroundVeryLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentBetween!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentBetweenLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentBetweenMedium!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentBetweenSmall!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentBetweenVeryLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentCenter!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentCenterLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentCenterMedium!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentCenterSmall!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentCenterVeryLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentEnd!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentEndLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentEndMedium!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentEndSmall!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentEndVeryLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentStart!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentStartLarge!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentStartMedium!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentStartSmall!alignment horizontal!public! !
!SBSNavigationTag categoriesFor: #justifyContentStartVeryLarge!alignment horizontal!public! !

