"Filed out from Dolphin Smalltalk 7"!

SBSGenericTag subclass: #SBSNavigationBarCollapseTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSNavigationBarCollapseTag guid: (GUID fromString: '{b31d2aa7-dee4-42ad-8f21-93f96c43c3df}')!
SBSNavigationBarCollapseTag comment: 'Used for grouping and hiding navbar contents by a parent breakpoint'!
!SBSNavigationBarCollapseTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSNavigationBarCollapseTag methodsFor!

collapse 	self class: 'collapse'!

defaultStyleClass	^'navbar-collapse'! !
!SBSNavigationBarCollapseTag categoriesFor: #collapse!options!public! !
!SBSNavigationBarCollapseTag categoriesFor: #defaultStyleClass!defaults!public! !

