"Filed out from Dolphin Smalltalk 7"!

SBSUnorderedListTag subclass: #SBSNavigationTabTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSNavigationTabTag guid: (GUID fromString: '{6e57fc00-a651-4ca1-ada1-21df523f8946}')!
SBSNavigationTabTag comment: 'I''m a Bootstrap navigation tab item.'!
!SBSNavigationTabTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSNavigationTabTag methodsFor!

defaultStyleClass	^'nav nav-tabs'!

initialize	super initialize.	self attributeAt: 'role' put: 'tablist'.!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !
!SBSNavigationTabTag categoriesFor: #defaultStyleClass!defaults!public! !
!SBSNavigationTabTag categoriesFor: #initialize!defaults!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentAround!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentAroundLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentAroundMedium!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentAroundSmall!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentAroundVeryLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentBetween!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentBetweenLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentBetweenMedium!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentBetweenSmall!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentBetweenVeryLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentCenter!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentCenterLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentCenterMedium!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentCenterSmall!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentCenterVeryLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentEnd!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentEndLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentEndMedium!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentEndSmall!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentEndVeryLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentStart!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentStartLarge!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentStartMedium!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentStartSmall!alignment horizontal!public! !
!SBSNavigationTabTag categoriesFor: #justifyContentStartVeryLarge!alignment horizontal!public! !

