"Filed out from Dolphin Smalltalk 7"!

SBSButtonTag subclass: #SBSOutlineButtonTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSOutlineButtonTag guid: (GUID fromString: '{29786f20-5210-4143-b501-e985569c39da}')!
SBSOutlineButtonTag comment: 'Bootstrap outlined buttons. It is like a regular form button - but by giving additional style options like bePrimary, or beSecondary, ... the button willhave an outlined look.'!
!SBSOutlineButtonTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSOutlineButtonTag methodsFor!

defaultModifier	^'outline'! !
!SBSOutlineButtonTag categoriesFor: #defaultModifier!defaults!public! !

