"Filed out from Dolphin Smalltalk 7"!

SBSListItemTag subclass: #SBSPageItemTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSPageItemTag guid: (GUID fromString: '{8befa317-420b-46e2-a7a5-c271ca01bcc6}')!
SBSPageItemTag comment: 'A page item for pagination'!
!SBSPageItemTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSPageItemTag methodsFor!

defaultStyleClass	^'page-item'! !
!SBSPageItemTag categoriesFor: #defaultStyleClass!defaults!public! !

