"Filed out from Dolphin Smalltalk 7"!

SBSAnchorTag subclass: #SBSPageLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSPageLinkTag guid: (GUID fromString: '{30e12e4b-dc4e-4c26-9ed8-008b1db680fd}')!
SBSPageLinkTag comment: 'A page link for Bootstrap pagination'!
!SBSPageLinkTag categoriesForClass!Bootstrap4-Core-Base! !
!SBSPageLinkTag methodsFor!

defaultStyleClass	^'page-link'! !
!SBSPageLinkTag categoriesFor: #defaultStyleClass!defaults!public! !

