"Filed out from Dolphin Smalltalk 7"!

TestCase subclass: #SBSRootComponentTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSRootComponentTest guid: (GUID fromString: '{3527087b-7ac6-427d-a18c-9f26443eb15e}')!
SBSRootComponentTest comment: 'SUnit tests for SBSRootComponent'!
!SBSRootComponentTest categoriesForClass!Bootstrap4-Core-Tests-Component! !
!SBSRootComponentTest methodsFor!

testCanBeRoot	self assert: SBSRootComponent canBeRoot ! !
!SBSRootComponentTest categoriesFor: #testCanBeRoot!public!tests! !

