"Filed out from Dolphin Smalltalk 7"!

Trait subclass: #SBSTRowItemAlignment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSTRowItemAlignment guid: (GUID fromString: '{6578187b-4f7e-4852-a6db-45105f7fd8bb}')!
SBSTRowItemAlignment comment: 'Vertical alignment of items in a row'!
!SBSTRowItemAlignment categoriesForClass!Unclassified! !
!SBSTRowItemAlignment methodsFor!

alignItemsBaseline	self class: 'align-items-baseline'!

alignItemsBaselineLarge	self class: 'align-items-lg-baseline'!

alignItemsBaselineMedium	self class: 'align-items-md-baseline'!

alignItemsBaselineSmall	self class: 'align-items-sm-baseline'!

alignItemsBaselineVeryLarge	self class: 'align-items-xl-baseline'!

alignItemsCenter	self class: 'align-items-center'!

alignItemsCenterLarge	self class: 'align-items-lg-center'!

alignItemsCenterMedium	self class: 'align-items-md-center'!

alignItemsCenterSmall	self class: 'align-items-sm-center'!

alignItemsCenterVeryLarge	self class: 'align-items-xl-center'!

alignItemsEnd	self class: 'align-items-end'!

alignItemsEndLarge	self class: 'align-items-lg-end'!

alignItemsEndMedium	self class: 'align-items-md-end'!

alignItemsEndSmall	self class: 'align-items-sm-end'!

alignItemsEndVeryLarge	self class: 'align-items-xl-end'!

alignItemsStart	self class: 'align-items-start'!

alignItemsStartLarge	self class: 'align-items-lg-start'!

alignItemsStartMedium	self class: 'align-items-md-start'!

alignItemsStartSmall	self class: 'align-items-sm-start'!

alignItemsStartVeryLarge	self class: 'align-items-xl-start'!

alignItemsStretch	self class: 'align-items-stretch'!

alignItemsStretchLarge	self class: 'align-items-lg-stretch'!

alignItemsStretchMedium	self class: 'align-items-md-stretch'!

alignItemsStretchSmall	self class: 'align-items-sm-stretch'!

alignItemsStretchVeryLarge	self class: 'align-items-xl-stretch'! !
!SBSTRowItemAlignment categoriesFor: #alignItemsBaseline!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsBaselineLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsBaselineMedium!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsBaselineSmall!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsBaselineVeryLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsCenter!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsCenterLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsCenterMedium!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsCenterSmall!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsCenterVeryLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsEnd!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsEndLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsEndMedium!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsEndSmall!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsEndVeryLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStart!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStartLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStartMedium!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStartSmall!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStartVeryLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStretch!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStretchLarge!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStretchMedium!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStretchSmall!alignment vertical!public! !
!SBSTRowItemAlignment categoriesFor: #alignItemsStretchVeryLarge!alignment vertical!public! !

