"Filed out from Dolphin Smalltalk 7"!

Trait subclass: #SBSTFlexboxContainer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSTFlexboxContainer guid: (GUID fromString: '{0ddda1f3-7514-4426-8ff2-d6bee6b8770f}')!
SBSTFlexboxContainer comment: 'A trait for flexbox container behaviour'!
!SBSTFlexboxContainer categoriesForClass!Unclassified! !
!SBSTFlexboxContainer methodsFor!

flex	self class: 'd-flex'!

flexColumn	self class: 'flex-column'!

flexColumnLarge	self class: 'flex-lg-column'!

flexColumnLargeReverse	self class: 'flex-lg-column-reverse'!

flexColumnMedium	self class: 'flex-md-column'!

flexColumnMediumReverse	self class: 'flex-md-column-reverse'!

flexColumnReverse	self class: 'flex-column-reverse'!

flexColumnSmall	self class: 'flex-sm-column'!

flexColumnSmallReverse	self class: 'flex-sm-column-reverse'!

flexColumnVeryLarge	self class: 'flex-xl-column'!

flexColumnVeryLargeReverse	self class: 'flex-xl-column-reverse'!

flexInline	self class: 'd-inline-flex'!

flexLarge	self class: 'd-lg-flex'!

flexLargeInline	self class: 'd-lg-inline-flex'!

flexMedium	self class: 'd-md-flex'!

flexMediumInline	self class: 'd-md-inline-flex'!

flexRow	self class: 'flex-row'!

flexRowLarge	self class: 'flex-lg-row'!

flexRowLargeReverse	self class: 'flex-lg-row-reverse'!

flexRowMedium	self class: 'flex-md-row'!

flexRowMediumReverse	self class: 'flex-md-row-reverse'!

flexRowReverse	self class: 'flex-row-reverse'!

flexRowSmall	self class: 'flex-sm-row'!

flexRowSmallReverse	self class: 'flex-sm-row-reverse'!

flexRowVeryLarge	self class: 'flex-xl-row'!

flexRowVeryLargeReverse	self class: 'flex-xl-row-reverse'!

flexSmall	self class: 'd-sm-flex'!

flexSmallInline	self class: 'd-sm-inline-flex'!

flexVeryLarge	self class: 'd-xl-flex'!

flexVeryLargeInline	self class: 'd-xl-inline-flex'! !
!SBSTFlexboxContainer categoriesFor: #flex!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumn!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnLarge!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnLargeReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnMedium!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnMediumReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnSmall!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnSmallReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnVeryLarge!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexColumnVeryLargeReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexInline!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexLarge!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexLargeInline!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexMedium!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexMediumInline!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexRow!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowLarge!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowLargeReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowMedium!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowMediumReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowSmall!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowSmallReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowVeryLarge!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexRowVeryLargeReverse!alignment direction!public! !
!SBSTFlexboxContainer categoriesFor: #flexSmall!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexSmallInline!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexVeryLarge!container!public! !
!SBSTFlexboxContainer categoriesFor: #flexVeryLargeInline!container!public! !

