"Filed out from Dolphin Smalltalk 7"!

SBSAbstractCanvasBrushTest subclass: #SBSTRowItemAlignmentTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSTRowItemAlignmentTest guid: (GUID fromString: '{2441a5cb-49d7-4499-8cdd-b3b752ac849e}')!
SBSTRowItemAlignmentTest comment: 'SUnit tests for SBSTRowItemAlignment'!
!SBSTRowItemAlignmentTest categoriesForClass!Bootstrap4-Core-Tests-Traits! !
!SBSTRowItemAlignmentTest methodsFor!

testRowAlignItemsBaseline	self		assert: [ :html | html row alignItemsBaseline ]		gives: '<div class="row align-items-baseline"></div>'	!

testRowAlignItemsBaselineLarge	self		assert: [ :html | html row alignItemsBaselineLarge ]		gives: '<div class="row align-items-lg-baseline"></div>'	!

testRowAlignItemsBaselineMedium	self		assert: [ :html | html row alignItemsBaselineMedium ]		gives: '<div class="row align-items-md-baseline"></div>'	!

testRowAlignItemsBaselineSmall	self		assert: [ :html | html row alignItemsBaselineSmall ]		gives: '<div class="row align-items-sm-baseline"></div>'	!

testRowAlignItemsBaselineVeryLarge	self		assert: [ :html | html row alignItemsBaselineVeryLarge ]		gives: '<div class="row align-items-xl-baseline"></div>'	!

testRowAlignItemsCenter	self		assert: [ :html | html row alignItemsCenter ]		gives: '<div class="row align-items-center"></div>'	!

testRowAlignItemsCenterLarge	self		assert: [ :html | html row alignItemsCenterLarge ]		gives: '<div class="row align-items-lg-center"></div>'	!

testRowAlignItemsCenterMedium	self		assert: [ :html | html row alignItemsCenterMedium ]		gives: '<div class="row align-items-md-center"></div>'	!

testRowAlignItemsCenterSmall	self		assert: [ :html | html row alignItemsCenterSmall ]		gives: '<div class="row align-items-sm-center"></div>'	!

testRowAlignItemsCenterVeryLarge	self		assert: [ :html | html row alignItemsCenterVeryLarge ]		gives: '<div class="row align-items-xl-center"></div>'	!

testRowAlignItemsEnd	self		assert: [ :html | html row alignItemsEnd ]		gives: '<div class="row align-items-end"></div>'	!

testRowAlignItemsEndLarge	self		assert: [ :html | html row alignItemsEndLarge ]		gives: '<div class="row align-items-lg-end"></div>'	!

testRowAlignItemsEndMedium	self		assert: [ :html | html row alignItemsEndMedium ]		gives: '<div class="row align-items-md-end"></div>'	!

testRowAlignItemsEndSmall	self		assert: [ :html | html row alignItemsEndSmall ]		gives: '<div class="row align-items-sm-end"></div>'	!

testRowAlignItemsEndVeryLarge	self		assert: [ :html | html row alignItemsEndVeryLarge ]		gives: '<div class="row align-items-xl-end"></div>'	!

testRowAlignItemsStart	self		assert: [ :html | html row alignItemsStart ]		gives: '<div class="row align-items-start"></div>'	!

testRowAlignItemsStartLarge	self		assert: [ :html | html row alignItemsStartLarge ]		gives: '<div class="row align-items-lg-start"></div>'	!

testRowAlignItemsStartMedium	self		assert: [ :html | html row alignItemsStartMedium ]		gives: '<div class="row align-items-md-start"></div>'	!

testRowAlignItemsStartSmall	self		assert: [ :html | html row alignItemsStartSmall ]		gives: '<div class="row align-items-sm-start"></div>'	!

testRowAlignItemsStartVeryLarge	self		assert: [ :html | html row alignItemsStartVeryLarge ]		gives: '<div class="row align-items-xl-start"></div>'	!

testRowAlignItemsStretch	self		assert: [ :html | html row alignItemsStretch ]		gives: '<div class="row align-items-stretch"></div>'	!

testRowAlignItemsStretchLarge	self		assert: [ :html | html row alignItemsStretchLarge ]		gives: '<div class="row align-items-lg-stretch"></div>'	!

testRowAlignItemsStretchMedium	self		assert: [ :html | html row alignItemsStretchMedium ]		gives: '<div class="row align-items-md-stretch"></div>'	!

testRowAlignItemsStretchSmall	self		assert: [ :html | html row alignItemsStretchSmall ]		gives: '<div class="row align-items-sm-stretch"></div>'	!

testRowAlignItemsStretchVeryLarge	self		assert: [ :html | html row alignItemsStretchVeryLarge ]		gives: '<div class="row align-items-xl-stretch"></div>'	! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsBaseline!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsBaselineLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsBaselineMedium!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsBaselineSmall!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsBaselineVeryLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsCenter!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsCenterLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsCenterMedium!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsCenterSmall!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsCenterVeryLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsEnd!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsEndLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsEndMedium!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsEndSmall!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsEndVeryLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStart!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStartLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStartMedium!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStartSmall!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStartVeryLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStretch!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStretchLarge!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStretchMedium!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStretchSmall!public!tests / layout / alignment vertical! !
!SBSTRowItemAlignmentTest categoriesFor: #testRowAlignItemsStretchVeryLarge!public!tests / layout / alignment vertical! !

