"Filed out from Dolphin Smalltalk 7"!

Trait subclass: #SBSTColumnSelfAlignment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSTColumnSelfAlignment guid: (GUID fromString: '{c4b8267d-9b9b-459c-a5ef-d047fa5a558d}')!
SBSTColumnSelfAlignment comment: 'Vertical alignment classes for columns'!
!SBSTColumnSelfAlignment categoriesForClass!Unclassified! !
!SBSTColumnSelfAlignment methodsFor!

alignCenter	self class: 'align-self-center'!

alignEnd	self class: 'align-self-end'!

alignStart	self class: 'align-self-start'! !
!SBSTColumnSelfAlignment categoriesFor: #alignCenter!alignment vertical!public! !
!SBSTColumnSelfAlignment categoriesFor: #alignEnd!alignment vertical!public! !
!SBSTColumnSelfAlignment categoriesFor: #alignStart!alignment vertical!public! !

