"Filed out from Dolphin Smalltalk 7"!

Trait subclass: #SBSTContentJustification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SBSTContentJustification guid: (GUID fromString: '{5809e46a-ad7a-4c7c-9bac-3aafa654bf2f}')!
SBSTContentJustification comment: 'A trait for flexbox alignment'!
!SBSTContentJustification categoriesForClass!Unclassified! !
!SBSTContentJustification methodsFor!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !
!SBSTContentJustification categoriesFor: #justifyContentAround!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentAroundLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentAroundMedium!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentAroundSmall!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentAroundVeryLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentBetween!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentBetweenLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentBetweenMedium!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentBetweenSmall!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentBetweenVeryLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentCenter!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentCenterLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentCenterMedium!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentCenterSmall!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentCenterVeryLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentEnd!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentEndLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentEndMedium!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentEndSmall!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentEndVeryLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentStart!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentStartLarge!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentStartMedium!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentStartSmall!alignment horizontal!public! !
!SBSTContentJustification categoriesFor: #justifyContentStartVeryLarge!alignment horizontal!public! !

